apiVersion: harness.io/v1
kind: Component
type: service
identifier: deveshharness_deployment_change_data_capture
name: change-data-capture
owner: group:account/IDP_Test
orgIdentifier: default
projectIdentifier: sd2
spec:
  lifecycle: production
  dependsOn:
  - Component:change-data-capture
  - Component:default-backend
  - Component:postgres
  - Component:harness-ingress-controller
  - Component:ssca-manager
  - Component:timescaledb-single-chart
  - Component:component-service
  - Component:mongodb-replicaset-chart
  subtype: Deployment
metadata:
  description: Kubernetes Deployment change-data-capture in namespace deveshharness
  annotations:
  tags:
  - kubernetes
  - auto-onboarded
  - deveshharness
  - deployment
