apiVersion: harness.io/v1
kind: component
orgIdentifier: default
projectIdentifier: sd2
type: Service
identifier: deveshharness_deployment_change_data_capture
name: "change-data-capture"
owner: group:account/IDP_Test
spec:
  lifecycle: production
  type: kubernetes
  subtype: Deployment
metadata:
  description: "Kubernetes Deployment in namespace deveshharness"
  annotations:
    backstage.io/kubernetes-id: change-data-capture
    backstage.io/kubernetes-namespace: deveshharness
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=change-data-capture,app.kubernetes.io/name=change-data-capture'
  tags:
    - kubernetes
    - auto-onboarded
    - deveshharness
    - deployment
