apiVersion: harness.io/v1
kind: Component
type: service
identifier: deveshharness_service_default_backend
name: default-backend
owner: group:account/IDP_Test
orgIdentifier: default
projectIdentifier: sd2
spec:
  lifecycle: production
  subtype: Service
metadata:
  description: Kubernetes Service default-backend in namespace deveshharness
  annotations:
    backstage.io/kubernetes-id: default-backend
    backstage.io/kubernetes-namespace: deveshharness
    backstage.io/kubernetes-label-selector: app.kubernetes.io/managed-by=Helm,created_by=terraform
  tags:
  - kubernetes
  - auto-onboarded
  - deveshharness
  - service
